# Generated by Django 5.0.1 on 2025-01-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db',
            name='age',
            field=models.IntegerField(),
        ),
    ]
