# Generated by Django 5.0.1 on 2025-01-17 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='content',
            new_name='text',
        ),
    ]
