# Generated by Django 5.0.1 on 2025-01-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_db_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='db',
            name='approvalstatus',
            field=models.BooleanField(default=False),
        ),
    ]
