# Generated by Django 5.0.1 on 2025-01-17 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_submitted_at_feedback_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
